### ISSUE TITLE
Failed to validate CalendarEvent

### ISSUE THREAD

**Issue by mariuszxeno** [Antoni-Czaplicki/vulcan-for-hassio#43] opened 2023-04-11 13:58 UTC
After update to core-2023.4.2
--

</body>
</html>
`Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345
First occurred: 07:45:05 (484 occurrences)
Last logged: 15:48:05

Update for calendar.vulcan_calendar_xxxx fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 82, in validate
    raise vol.Invalid("Expected all values to have a timezone")
voluptuous.error.Invalid: Expected all values to have a timezone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected all values to have a timezone

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/vulcan/calendar.py", line 158, in async_update
    self._event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected all values to have a timezone
`

**Comment by Antoni-Czaplicki** [comment] 2023-04-13 17:15
Duplicate of #42

**Closed by Antoni-Czaplicki** 2023-04-13 17:15 UTC
