### ISSUE TITLE
Niedostępność encji w HA core 2023.3.0

### ISSUE THREAD

**Issue by mariuszxeno** [Antoni-Czaplicki/vulcan-for-hassio#40] opened 2023-03-02 13:45 UTC
Po aktualizacji HA do najnowszej wersji tj. core-2023.3.0 wszystkie encje stały się niedostępne.

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 14:40:04 (3 occurrences)
Last logged: 14:40:12

Unable to install package vulcan-api==2.2.1: ERROR: Cannot install vulcan-api==2.2.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 14:40:12 (1 occurrences)
Last logged: 14:40:12

Setup failed for custom integration vulcan: Requirements for vulcan not found: ['vulcan-api==2.2.1'].

**Comment by yarpen1** [comment] 2023-03-02 14:44
Mam ten sam problem po aktualizacji HA do wersji core-2023.3.0

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 10:53:10 (1 occurrences)
Last logged: 10:53:10

Setup failed for custom integration vulcan: Requirements for vulcan not found: ['vulcan-api==2.2.1'].

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 10:52:53 (3 occurrences)
Last logged: 10:53:10

Unable to install package vulcan-api==2.2.1: ERROR: Cannot install vulcan-api==2.2.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by Antoni-Czaplicki** [comment] 2023-03-02 14:46
Duplicate of #35

**Closed by Antoni-Czaplicki** 2023-03-02 14:46 UTC
