### ISSUE TITLE
Integration with std version of UONET Vulcan does not work

### ISSUE THREAD

**Issue by keysim86** [Antoni-Czaplicki/vulcan-for-hassio#53] opened 2024-03-04 21:21 UTC
Hello,
When I try to run the integration I provide the data generated on the Vulcan website, click ok and receive the error below.
![Zrzut ekranu 2024-03-04 220726](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/153317279/ab1ba9fc-fdb9-46e5-bfcc-f810efe0a749)

Then I look at the Vulcan website and see that the certificate has been issued and the Home Assistant device registered, but only on the Vulcan website.
![Zrzut ekranu 2024-03-04 220739](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/153317279/d0194eb4-de29-49e2-a9ab-231d37c03eef)

> 2024-03-04 22:18:40.239 INFO (MainThread) [client] Generating key pair...
2024-03-04 22:18:40.362 INFO (MainThread) [client] Getting Firebase token...
2024-03-04 22:18:40.904 INFO (MainThread) [client] Generated for Home Assistant, sha1: c92d35331d0bdaea780838a3643f80ad92aea5ee
2024-03-04 22:18:40.905 INFO (MainThread) [client] Getting Vulcan components...
2024-03-04 22:18:41.003 INFO (MainThread) [client] Registering to gminaxxxxx...
2024-03-04 22:18:41.213 INFO (MainThread) [client] Successfully registered as xxxxxxx@gmail.com
2024-03-04 22:18:41.797 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vulcan/config_flow.py", line 95, in async_step_auth
    students = await client.get_students()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/_client.py", line 61, in get_students
    self._students = await Student.get(self._api)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/model/_student.py", line 79, in get
    return [Student.load(student) for student in data]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vulcan/model/_serializable.py", line 49, in load
    return to_model(cls, data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
            ^^^^^^^^^^^^
  File "", line 11, in __init__
    __attr_validator_class_(self, __attr_class_, self.class_)
  File "/usr/local/lib/python3.12/site-packages/attr/validators.py", line 106, in __call__
    raise TypeError(
TypeError: ("'class_' must be (,) (got None that is a ).", Attribute(name='class_', default=NOTHING, validator=,)>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({'key': 'ClassDisplay'}), type=, converter=, kw_only=False, inherited=False, on_setattr=None, alias='class_'), (,), None)

HA Version: 2024.2.5
UONET Version: 0.15.1

**Comment by Antoni-Czaplicki** [comment] 2024-03-05 08:07
Duplicate of #52

**Closed** 2024-03-05 08:07 UTC
